### ISSUE TITLE
Update packagist.org versions

### ISSUE THREAD

**Issue by xorti** [alchemy-fr/Media-Alchemyst#34]
Please update packagist versions in order to make version 0.5.3 available.

https://packagist.org/packages/media-alchemyst/media-alchemyst

Thanks

**Comment by jygaulier** [comment]
Hi,
Alchemy is not a maintainer of this packagist repo, please ask Romain
Neutron who leaved the company years ago.
Next week I will talk about options :
- ask Romain to transfer / add Alchemy as maintainer to the current repo
- publish to a new packagist "Alchemy/media-alchemyst" repo
- ... any other option
with other people at Alchemy.

sorry for the delay, but we (Alchemy) are mostly focused on our main
application, without much time to update libs...

best regards,
JY Gaulier



Le mar. 22 oct. 2019 à 16:21, Jorge Sá Pereira <notifications@github.com> a
écrit :

**Comment by jygaulier** [comment]
thks to Romain, 0.5.3 has been pushed on packagist and Alchemy granted as maintainer.
@romainneutron : merci Romain :)
