### ISSUE TITLE
Wrong version requirement for php-ffmpeg?

### ISSUE THREAD

**Issue by iannz-wai** [alchemy-fr/Media-Alchemyst#41]
I think that there might be a wrong version requirement for php-ffmpeg/php-ffmpeg
As stated it is 4.1 but according to https://packagist.org/packages/php-ffmpeg/php-ffmpeg it is only at 0.14. I'm new to this so it might be my misunderstanding. Thanks in advance, Ian

**Comment by nmaillat** [comment]
Hello, This is fix by pr #42, Nicolas
